"""baseline schema

Revision ID: f79d50b8e5d9
Revises: 
Create Date: 2026-07-28 16:05:13.975953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f79d50b8e5d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('venue', sa.String(length=160), nullable=False),
    sa.Column('neighborhood', sa.String(length=80), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vibe', sa.String(length=32), nullable=False),
    sa.Column('price_tier', sa.String(length=16), nullable=False),
    sa.Column('price_note', sa.String(length=120), nullable=True),
    sa.Column('hook', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('ticket_url', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_vibe', ['vibe'], unique=False)
        batch_op.create_index('ix_events_window', ['is_active', 'start_at', 'end_at'], unique=False)

    op.create_table('insider_tips',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('venue', sa.String(length=160), nullable=True),
    sa.Column('vibe', sa.String(length=32), nullable=True),
    sa.Column('tip', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insider_tips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insider_tips_venue'), ['venue'], unique=False)
        batch_op.create_index(batch_op.f('ix_insider_tips_vibe'), ['vibe'], unique=False)

    op.create_table('share_lists',
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('event_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('share_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_lists_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_lists_expires_at'))

    op.drop_table('share_lists')
    with op.batch_alter_table('insider_tips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insider_tips_vibe'))
        batch_op.drop_index(batch_op.f('ix_insider_tips_venue'))

    op.drop_table('insider_tips')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_window')
        batch_op.drop_index('ix_events_vibe')

    op.drop_table('events')
    # ### end Alembic commands ###
